### ISSUE TITLE
Storage Access API

### ISSUE THREAD

**Issue by andywang219** [cfredric/chrome-storage-access-api#11]
Hi @cfredric,

I just to confirm that the Storage Access API will be enabled by default when Chrome rolls out the third-party cookie deprecation correct?

**Comment by cfredric** [comment]
Yes, Chrome enabled the Storage Access API by default in https://chromiumdash.appspot.com/commit/a16439afb42e4635d62069314e3b5cf8039a6c26 which is in Chrome 120, currently in the Beta channel. Chrome 120 is scheduled for stable release on 5 December 2023 according to https://chromiumdash.appspot.com/schedule.
