### ISSUE TITLE
Does storage Access API applicable for other type of storages too? 

### ISSUE THREAD

**Issue by jagadeeshaby** [cfredric/chrome-storage-access-api#3]
As of today Firefox and Safari does only support same site storage access to Local storage and Shared worker, could you confirm the same for Chrome?  Chrome/edge today allow access to cross site access to shared worker and local storage.

**Comment by cfredric** [comment]
Can you clarify what you mean by "same site storage access"? Or better yet, give more detail about your use case?

Chrome does support LocalStorage and Shared Workers in same-site contexts. Chrome also supports use of LocalStorage and Shared Workers in cross-site contexts -- but you should be aware that those APIs are being partitioned as part of the [Storage Partitioning](https://groups.google.com/u/1/a/chromium.org/g/blink-dev/c/24hK6DKJnqY/m/aHSXjm01AgAJ) project.

**Comment by jagadeeshaby** [comment]
> Can you clarify what you mean by "same site storage access"? Or better yet, give more detail about your use case?

In our case cookies are fine with this API, we also make use of local storage and shared worker.  

basically when our app loads , it creates a shared worker for data sync use cases, so What i have observed is loading our app in site11.com  and site22.com top level sites results in 2 shared workers being spun up. 

Seems like this is inline with the storage access specs, but likely not implemented yet in edge//chrome? because when testing the same on these browsers i could see that shared worker and local storage shared across the top level sites. 

- Could you confirm if shared worker has access across top level sites? 
- if not do you any other alternatives i should look into?  having 2 shared worker running makes our whole app useless.

**Comment by jagadeeshaby** [comment]
>There's an https://github.com/privacycg/storage-access/issues/102 for this support, and I see that you recently opened a https://github.com/privacycg/storage-access/issues/175 for it as well.

may be best suited for the other APi spec, but do you know Chrome is doing anything on this line to provide accesss? 

Also do you happened to know any relevant enterprise policies which would help to provide the cross storage access especially for local storage and shared worker ?

**Comment by cfredric** [comment]
> may be best suited for the other APi spec, but do you know Chrome is doing anything on this line to provide accesss?

Chrome engineers are [participating](https://github.com/privacycg/storage-access/issues/102#issuecomment-1604176122) in the discussion on the original issue, but I don't have more information to share than that.

> Also do you happened to know any relevant enterprise policies which would help to provide the cross storage access especially for local storage and shared worker ?

Yes, there are two enterprise policies: https://chromeenterprise.google/policies/atomic-groups/#ThirdPartyStoragePartitioningSettings.

**Comment by jagadeeshaby** [comment]
>Third-party storage partitioning is on by default for some users as of M113 

Wow, Storage partition is live already!!!

**Comment by cfredric** [comment]
I'm going to tentatively close this issue since I think I've answered your questions, but feel free to reopen or open new issues if you have more questions. Thanks!
