### ISSUE TITLE
Creating Tests for Request Storage Access

### ISSUE THREAD

**Issue by andywang219** [cfredric/chrome-storage-access-api#8]
Hello,

I am currently trying to write tests revolving around the Request Storage Access API, but I have hit a few blockers. My test suites utilizes Cypress. Here is the general idea of the tests I'm writing:

1. Load my application in an iframe, making it third-party and needing Request Storage Access API
2. Click a button that would trigger the request storage access api
3. Click "Allow" in the Chrome prompt
4. Check if my application loads properly afterwards in the iframe

Some blockers that I am facing and was hoping to see if there are any workarounds:
1. There is no way for Cypress to access the Chrome prompt and click "Allow" since the prompt is not in the HTML
2. There is no way for Cypress to clear permission granted after clicking "Allow"
    - Cypress does not allow navigating to chrome://settings/content/storageAccess, which is where an user would go to to reset permissions

Are there any known workarounds for the two blockers above such as Chrome switches? For my Chrome parameters, I am currently using the following:
`--test-third-party-cookie-phaseout`
`--enable-features=StorageAccessAPI,PermissionStorageAccessAPI`

I know Cypress has a Test Isolation concept that clears the browser context for each test run, but it doesn't seem to clear the request storage access permissions. I am assuming this is because the Request Storage Access API is fairly new?

Thanks!

**Comment by cfredric** [comment]
Hi @andywang219, I'm not familiar with Cypress but from Chrome's perspective, you should test the Storage Access API the same way you would test any other browser permission (e.g. geolocation, microphone, camera, etc.). If Cypress has a way to handle other permission types, that should work for the `storage-access` permission as well.

([This](https://dev.to/kamranayub/controlling-browser-permissions-in-cypress-end-to-end-tests-5d7b) post makes it seem like Cypress doesn't have official support, but there are open-source packages that offer support for testing permissions? I haven't looked in depth though.)

As this is more of a Cypress issue than a Chrome issue, and Chrome can't really do anything here, I'm going to close this issue.
